//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Groups = new HashSet<Group>();
            this.Locations = new HashSet<Location>();
        }
    
        public int AddressID { get; set; }
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Attention { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateProvinceID { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string AddressPhone { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> CreatedByPersonID { get; set; }
        public Nullable<int> ModifiedByPersonID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
