//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int CustomerPaymentID { get; set; }
        public long CustomerID { get; set; }
        public int PriceID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string RecurringPaymentID { get; set; }
        public decimal PaymentAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Price Price { get; set; }
    }
}
