//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public GroupMember()
        {
            this.GroupMemberContactMethods = new HashSet<GroupMemberContactMethod>();
        }
    
        public long GroupMemberID { get; set; }
        public int GroupMemberTypeID { get; set; }
        public long CustomerID { get; set; }
        public int GroupID { get; set; }
        public long PersonID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long CreatedByPersonID { get; set; }
        public Nullable<long> ModifiedByPersonID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Group Group { get; set; }
        public virtual GroupMemberType GroupMemberType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual ICollection<GroupMemberContactMethod> GroupMemberContactMethods { get; set; }
    }
}
