//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int GroupID { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public int CustomerID { get; set; }
        public int GroupTypeID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> CreateByUserID { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
