//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMemberContactMethod
    {
        public long GroupMemberContactMethodID { get; set; }
        public long GroupMemberID { get; set; }
        public long PersonContactMethodID { get; set; }
    
        public virtual GroupMember GroupMember { get; set; }
        public virtual PersonContactMethod PersonContactMethod { get; set; }
    }
}
