//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMemberType
    {
        public GroupMemberType()
        {
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int GroupMemberTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
