//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContactMethod
    {
        public PersonContactMethod()
        {
            this.GroupMemberContactMethods = new HashSet<GroupMemberContactMethod>();
        }
    
        public long PersonContactMethodID { get; set; }
        public long PersonID { get; set; }
        public int ContactMethodID { get; set; }
        public int ContactMethodQualifierID { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GroupMemberContactMethod> GroupMemberContactMethods { get; set; }
        public virtual Person Person { get; set; }
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual ContactMethodQualifier ContactMethodQualifier { get; set; }
    }
}
