//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhone
    {
        public long PersonPhoneID { get; set; }
        public long PersonID { get; set; }
        public int PhoneTypeID { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
    }
}
