//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public Price()
        {
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int PriceID { get; set; }
        public int PriceListID { get; set; }
        public int BillingIntervalID { get; set; }
        public decimal Price1 { get; set; }
    
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual BillingInterval BillingInterval { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
