//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringPayment
    {
        public int RecurringPaymentID { get; set; }
        public int CustomerID { get; set; }
        public int SubscriptionID { get; set; }
        public System.DateTime SubscriptionStartDate { get; set; }
        public System.DateTime SubscriptionExpireDate { get; set; }
        public Nullable<System.DateTime> SubscriptionCancelDate { get; set; }
        public bool Active { get; set; }
        public decimal IntervalLength { get; set; }
        public string IntervalUnit { get; set; }
        public decimal TotalOccurences { get; set; }
        public decimal TrialOccurences { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal TrialAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
