//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumRunDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticList
    {
        public int StaticListID { get; set; }
        public string Value { get; set; }
        public string MiscListName { get; set; }
        public int ListSequence { get; set; }
    }
}
